# ===============================
# DATABASE CONFIG (PROD)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/EmployeeDataManagement
spring.datasource.username=rohit
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Production optimizations
spring.jpa.show-sql=false

# Connection pool tuning
spring.datasource.hikari.maximum-pool-size=10

# Minimal logging
logging.level.org.hibernate.SQL=ERROR
logging.level.org.springframework=INFO