spring.application.name=SprinBooot-JPA-demo

# Common JPA config
spring.jpa.hibernate.ddl-auto=update

spring.profiles.active=dev

# Cache config (common)
spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.default_batch_fetch_size=10
spring.jpa.properties.hibernate.cache.use_query_cache=true
spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.jcache.JCacheRegionFactory
spring.jpa.properties.hibernate.javax.cache.provider=org.ehcache.jsr107.EhcacheCachingProvider

#======================================================
#Actutor configurations
#======================================================

# expose only required endpoints
management.endpoints.web.exposure.include=health,info,metrics

# optional: show full health details
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/admin/actuator

#======================================================
#Admin user for actuator access
#======================================================

spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN

